matter-labs/teepot

.github/workflows/nix.yml
docker does not support pushing and tagging with a different name in one go as podman does.
=> ci: fix docker push

Cargo.lock, bin/tee-key-preexec/Cargo.toml, bin/tee-key-preexec/src/main.rs
No need to hash the public key for the attestation report data.
=> fix(tee-key-preexec): don't hash public key

packages/container-self-attestation-test-sgx-azure/default.nix, packages/container-self-attestation-test-sgx-dcap/default.nix, packages/container-vault-admin-sgx-azure/default.nix, packages/container-vault-sgx-azure/default.nix, packages/container-vault-start-config/default.nix, packages/container-vault-unseal-sgx-azure/default.nix, packages/container-vault-unseal/default.nix, packages/container-verify-attestation-sgx-azure/default.nix, packages/container-verify-attestation-sgx-dcap/default.nix, packages/teepot/default.nix
`curl` and `openssl` have to be specified with `.out`
=> fix: cleanup the nix packages

flake.lock, teepot-crate.nix
gramine 1.7 now supports eventfd.
Update nixsgx flake and remove the `RUSTFLAGS`.
=> feat: remove mio workaround with gramine 1.7

.github/workflows/nix.yml
This commit updates the GitHub workflows to run on the custom 'matterlabs-ci-runner' and push Docker images to Google Artifact Registry. Additionally, it refines event conditions, separates build ID generation for normal pushes and tag pushes, and introduces tagging workflow for '*-sgx-*' tags.
=> chore: Update GitHub actions to run on custom runner and push to infra

.github/workflows/nix.yml
This update removes usage of cachix/cachix-action and updates job runner from ubuntu-latest to matterlabs-ci-runner in the GitHub Actions workflow. New configurations have been added for trusted-public-keys and substituters.
=> chore: update GitHub Actions workflow configuration

Cargo.lock, Cargo.toml, bin/tee-key-preexec/Cargo.toml, bin/tee-key-preexec/src/main.rs, deny.toml
Rationale: we already have secp256k1 in our dependencies, as suggested by Igor:
https://github.com/matter-labs/zksync-era/pull/2333#discussion_r1656531731
=> Replace secp256k1 with k256 crate

README.md, flake.nix, packages/container-vault-sgx-azure/default.nix
* fix: `sgx.nonpie_binary` option is deprecated
see https://github.com/gramineproject/gramine/pull/1187
* chore: replace cache in `flake.nix` nixConfig
* docs: adapt README.md to reality
=> chore: misc fixes

packages/container-vault-unseal-sgx-azure/default.nix
use the correct environment variable name... sigh
=> fix(container-vault-unseal-sgx-azure): correct `VAULT_AUTH_TEE_SHA256_FILE`

Cargo.lock, Cargo.toml, bin/verify-attestation/Cargo.toml, bin/verify-attestation/src/main.rs
The zksync crates [have recently been published on crates.io](https://crates.io/keywords/zksync?sort=new). Let's take advantage of them! Specifically, we are replacing `alloy-primitives` with `zksync_basic_types` to avoid the additional transitive dependencies introduced by `alloy`.
=> fix(verify-attestation): simplify dependencies

packages/container-vault-start-config/config.hcl
The vault instances lose the raft leader status, while loading the `vault-auth-tee` plugin, because the gramine enviroment slows down the `execve` significantly.
Using `performance_multiplier` relaxes the timeouts for the raft protocol.
see also: https://github.com/hashicorp/vault/issues/28009
=> fix: use `performance_multiplier`

flake.lock, packages/container-vault-sgx-azure/default.nix
- Updated the flake.lock for nixsgx dependency with new revision to get a patched gramine https://github.com/matter-labs/nixsgx/pull/54
- Enabled `sys.insecure__allow_eventfd` to support recent golang changes in the `netpoll` implementation
=> fix(vault): maybe fix `netpollBreak` issues

packages/container-vault-sgx-azure/default.nix
Removed the sys.insecure__allow_eventfd setting, because gramine has a secure eventfd implementation since
[v1.7](https://github.com/gramineproject/gramine/releases/tag/v1.7).
=> fix(container-vault-sgx-azure): remove insecure eventfd setting

.github/workflows/nix.yml, Cargo.lock, Cargo.toml, bin/verify-era-proof-attestation/Cargo.toml, bin/verify-era-proof-attestation/src/main.rs, flake.nix, packages/cargoClippy/default.nix, packages/container-verify-era-proof-attestation-sgx/default.nix, packages/teepot/default.nix, shells/teepot/default.nix, teepot-crate.nix
This is another variant of the binary tool for verifying attestation and the signature of a given batch. Unlike the [existing tool](https://github.com/matter-labs/teepot/tree/main/bin/verify-attestation), this variant does not require you to provide two separate files – one for the attestation and one for the signature. Instead, it automatically fetches both from the RPC node.
Unfortunately, after discussing with @popzxc, we found that there is no way to reuse the RPC client because our published crates on crates.io are outdated and do not include the recently merged TEE-specific code changes. To be fixed in the future.
To use `verify-rpc-attestation`, run:
```
$ nix build -L .#container-verify-era-proof-attestation-sgx
$ export IMAGE_TAG=$(docker load -i result | grep -Po 'Loaded …
```
=> feat(verify-attestation): RPC attestation and batch signature verification binary

Cargo.lock, bin/tee-key-preexec/Cargo.toml, bin/tee-key-preexec/src/main.rs
- Introduced `clap` for command-line argument parsing.
- Replaced manual argument handling with `clap`'s derived `Args` struct.
- Updated environmental variables to use dynamic prefixes.
=> feat(tee-key-preexec): add cmdline arg for env prefix

shells/teepot/default.nix
The shellHook statement has been added to export OPENSSL_NO_VENDOR as 1. This should prevent building the vendored version of openssl.
=> chore(nix): set shell environment for openssl

Cargo.lock, Cargo.toml, bin/verify-era-proof-attestation/Cargo.toml, bin/verify-era-proof-attestation/src/args.rs, bin/verify-era-proof-attestation/src/client.rs, bin/verify-era-proof-attestation/src/main.rs, bin/verify-era-proof-attestation/src/proof.rs, bin/verify-era-proof-attestation/src/verification.rs
This PR introduces TEE Prover continuous mode with attestation policies.
Attestation policies are a set of criteria that determine whether an SGX attestation should be considered valid or invalid. In practice, this means checking against a specified set of [`mrsigners`][1], [`mrenclaves`][1], and [TCB levels][2]. If the attestation’s `mrenclave`/`mrsigner`/TCB levels matches those in the provided `--sgx-mrenclaves`/`--sgx-mrsigners`/`--sgx-allowed-tcb-levels`, we treat the attestation as successfully verified. Otherwise, the attestation is considered invalid.
The `--continuous` mode for the TEE Prover allows it to run continuously, verifying new batches exposed by the node's RPC API in real-time.
To try it out, run the following commands:
```
$ nix build -L …
```
=> feat(verify-era-proof-attestation): added continuous mode with attestation policies

Cargo.lock, bin/verify-era-proof-attestation/Cargo.toml, bin/verify-era-proof-attestation/src/proof.rs
Following Anton's suggestion, we have switched to hex serialization for API/RPC requests and responses. Previously, we used default JSON serialization for Vec<u8>, which resulted in a lengthy comma-separated list of integers.
This change standardizes serialization, making it more efficient and reducing the size of the responses. The previous format, with a series of comma-separated integers for pubkey-like fields, looked odd.
Then:
```
curl -X POST\
-H "Content-Type: application/json" \
--data '{"jsonrpc": "2.0", "id": 1, "method": "unstable_getTeeProofs", "params": [491882, "Sgx"] }' \
https://mainnet.era.zksync.io
{"jsonrpc":"2.0","result":[{"attestation":[3,0,2,0,0,0,0,0,10,<dozens of comma-separated integers here>
```
Now:
```
$ curl -X POST \
-H "Content-Type: application/json" \ …
```
=> feat(tee): use hex deserialization for RPC requests

flake.nix
- Removed the unnecessary crane input follow from flake.nix.
```
warning: input 'crane' has an override for a non-existent input 'nixpkgs'
```
=> fix(flake.nix): remove redundant crane input follow

bin/verify-era-proof-attestation/src/main.rs, bin/verify-era-proof-attestation/src/proof.rs
Currently, the [TEE verifier][1] – the tool for continuous SGX attestation and batch signature verification – is [stuck][2] on batches that failed to be proven and are marked as `permanently_ignored`. The tool should be able to distinguish between batches that are permanently ignored (and should be skipped) and batches that have failed but will be retried. This PR enables that distinction.
This commit goes hand in hand with the following PR: https://github.com/matter-labs/zksync-era/pull/3321
[1]: https://github.com/matter-labs/teepot/blob/main/bin/verify-era-proof-attestation/src/main.rs
[2]: https://grafana.matterlabs.dev/goto/unFqf57Hg?orgId=1
=> feat(verifier): don't retry verifying permanently ignored batches

bin/vault-admin/src/main.rs, bin/verify-era-proof-attestation/src/main.rs, crates/teepot/src/log/mod.rs
- Modified the `setup_logging` function to return a `Subscriber`, improving flexibility and reuse.
- Integrated `tracing::subscriber::set_global_default` in the main functions to establish the logging subscriber globally.
- Added configurations for span events and control over file and line information display.
=> refactor(logging): enhance logging setup and usage

Cargo.lock, Cargo.toml, bin/rtmr-calc/Cargo.toml, bin/rtmr-calc/src/main.rs, bin/sha384-extend/Cargo.toml, bin/sha384-extend/src/main.rs, bin/tdx-extend/Cargo.toml, bin/tdx-extend/src/main.rs, crates/teepot/src/lib.rs, crates/teepot/src/tdx/mod.rs, crates/teepot/src/tdx/rtmr.rs, packages/teepot/default.nix
This enables pre-calculating the TDX rtmr[1,2,3] values for an attested boot process.
=> feat: add tdx-extend, sha384-extend and rtmr-calc

packages/tdx_google/configuration.nix, systems/x86_64-linux/tdxtest/default.nix
- Enable Vector service and configure OpenTelemetry source.
- Add sinks for logs output to console and Kafka.
- Configure environment setup for Kafka using GCP metadata API.
-  removed commented-out ssh debugging
- Configured resolved service, disabling LLMNR and MulticastDNS
for improved resolution settings.    
- Removed commented-out Prometheus Node config
=> feat(google-tdx): add vector pushing to kafka for logging

packages/tdx_google/configuration.nix
- Set journald console to `/dev/ttyS0` for improved logging.
- Disable `serial-getty@ttyS0` service to avoid conflicts.
=> feat(configuration): update journald and serial settings

packages/tdx_google/configuration.nix, packages/tdx_google/container.nix, packages/tdx_google/metadata.nix, packages/tdx_google/vector.nix
- Split `tdx_google/configuration.nix` into smaller modules: `vector.nix`, and `container.nix`.
- Simplified the main configuration by leveraging modular imports for better readability and maintainability.    
- Replaced hardcoded metadata-fetching logic with shared metadata service.
- Removed custom pre-start scripts and refactored environment handling.
- Updated Vector configuration to include custom field transformations.
- Streamlined container startup process and ensured proper cleanup.  
- Removed unused `teepot` package from system environment
=> refactor(tdx_google): modularize tdx_google configuration

packages/tdx_google/container.nix
- Mount `/sys/kernel/config` to enable attestation for TDX containers.
- Ensures compatibility with TDX guest measurements during runtime.
=> feat(tdx_google): add support for attestation in container

packages/tdx_google/metadata.nix
- Introduce `ExecPostStop` handler to trigger reboot after 5 minutes.
=> feat(tdx_google): add onFailure action to reboot on metadata.service errors

bin/rtmr-calc/src/main.rs, bin/tee-key-preexec/src/main.rs, crates/teepot/src/tdx/rtmr.rs
- Added `UEFI_MARKER_DIGEST_BYTES` constant for TDX RTMR extension.
- Implemented RTMR3 extension in `tee-key-preexec` for TDX attestation flow.
- Updated `rtmr-calc` to use `UEFI_MARKER_DIGEST_BYTES` for RTMR1 extension.
=> feat(tdx): add TDX RTMR extension support with UEFI marker

bin/verify-era-proof-attestation/src/verification.rs
- Add fallback for missing RecoveryId in 64-byte signatures.
- Improve error context for invalid signature length.
- Add debug and trace logs for better diagnosis during verification.
=> fix(verify-era-proof-attestation): handle missing RecoveryId signatures

Cargo.toml, bin/tee-vault-admin/src/main.rs, bin/tee-vault-unseal/src/main.rs, bin/vault-admin/README.md, bin/vault-admin/src/main.rs, crates/teepot/src/client/mod.rs
New `rustls` needs global install of default `CryptoProvider`.
=> fix(teepot-vault): use `ring` as `CryptoProvider` for `rustls`

packages/tdx_google/container.nix
- Include iproute2 in the container path for required networking tools.
- Add a script to wait for vector to initialize before proceeding.
=> feat(tdx_google): add iproute2 and vector initialization wait

Cargo.lock, bin/sha384-extend/Cargo.toml, bin/sha384-extend/src/main.rs, bin/tdx-extend/src/main.rs, crates/teepot/src/lib.rs, crates/teepot/src/util/mod.rs
- Refactor `sha384-extend` to include digest padding and validation.
- Add `extend_sha384` function for hex-string-based digest extension.
- Introduce comprehensive test coverage for edge cases and errors.
=> feat(bin): enhance SHA384 extend utility with padding and tests

.github/workflows/nix.yml, assets/gcloud-deploy.sh, bin/tee-self-attestation-test/README.md, examples/README.md, examples/k8s/vault-1-pod.yaml, examples/k8s/vault-2-pod.yaml, examples/k8s/vault-3-pod.yaml, examples/k8s/vault-unseal-pod-0.yaml, examples/k8s/vault-unseal-pod-1.yaml, examples/k8s/vault-unseal-pod-2.yaml, systems/x86_64-linux/tdxtest/default.nix, systems/x86_64-linux/tdxtest/web-root/computeMetadata/v1/instance/attributes/container_image
Updated the workflow to push container images to GitHub Container Registry instead of Docker Hub. Added a login step for GHCR and updated image tagging and pushing commands accordingly.
=> feat(ci): switch to GitHub Container Registry for images

bin/rtmr-calc/src/main.rs, bin/sha384-extend/src/main.rs, bin/tee-self-attestation-test/src/main.rs, bin/verify-attestation/src/main.rs, bin/verify-era-proof-attestation/src/client/json_rpc.rs, bin/verify-era-proof-attestation/src/core/config.rs, bin/verify-era-proof-attestation/src/core/types.rs, bin/verify-era-proof-attestation/src/error.rs, bin/verify-era-proof-attestation/src/main.rs, bin/verify-era-proof-attestation/src/processor/batch_processor.rs, bin/verify-era-proof-attestation/src/processor/continuous_processor.rs, bin/verify-era-proof-attestation/src/processor/mod.rs, bin/verify-era-proof-attestation/src/processor/one_shot_processor.rs, bin/verify-era-proof-attestation/src/proof/fetcher.rs, bin/verify-era-proof-attestation/src/proof/parsing.rs, bin/verify-era-proof-attestation/src/proof/types.rs, bin/verify-era-proof-attestation/src/verification/attestation.rs, bin/verify-era-proof-attestation/src/verification/batch.rs, bin/verify-era-proof-attestation/src/verification/policy.rs, bin/verify-era-proof-attestation/src/verification/signature.rs, crates/intel-dcap-api/src/client/helpers.rs, crates/teepot/src/config/mod.rs, crates/teepot/src/ethereum/mod.rs, crates/teepot/src/log/mod.rs, crates/teepot/src/prover/reportdata.rs, crates/teepot/src/quote/error.rs, crates/teepot/src/quote/mod.rs, crates/teepot/src/quote/phala.rs, crates/teepot/src/quote/tcblevel.rs, crates/teepot/src/sgx/sign.rs
- Move const items to top level of files
- Inline format variables 
- Use conversion methods instead of casts where infallible
- Improve type ergonomics by correctly applying and removing references
- Replace a single variant match with an if let
- Combine equivalent match branches
- Improve punctuation consistency and readability
- Remove a single redundant continue at the end of a loop
=> refactor: many small code quality improvements

crates/teepot-vault/src/client/mod.rs, crates/teepot/src/sgx/mod.rs
- Removed custom `Quote` structure and parsing logic in `teepot/src/sgx/mod.rs`.
- Updated references to use the library-provided `Quote` methods, such as `Quote::parse` and `get_report_data`.
- Simplified code and reduced redundancy by leveraging existing library functionality.
=> refactor: replace custom Quote parsing with library version

Cargo.toml
- Set `teepot`, `teepot-tee-quote-verification-rs`, and `teepot-vault` crate versions to 0.6.0 in `Cargo.toml`.
- Ensures consistency with the planned 0.6.0 release preparation.
=> chore(deps): update `teepot` crates to version 0.6.0

crates/teepot-tdx-attest-rs/README.md, crates/teepot-tdx-attest-sys/README.md, crates/teepot-tee-quote-verification-rs/README.md, crates/teepot-vault/README.md, crates/teepot/README.md
- Added comprehensive README files for the following new crates:
- `teepot`
- `teepot-tdx-attest-rs`
- `teepot-tdx-attest-sys`
- `teepot-tee-quote-verification-rs`
- `teepot-vault`
- Each includes an overview, usage examples, installation instructions, and licensing details.
=> docs: add README files for teepot-related crates
